/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compressor;

import org.xerial.snappy.Snappy;
import java.io.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import compressor.Compressor; 

public class App {

    static Compressor compressor = new Compressor(); 

    public static void main(String[] args) {
        String inputFileName = "/home/winston/Documents/GitHub/Prime-Calculator/compression/Java/compressor/app/src/main/java/compressor/test.txt"; 
        String outputFileName = "/home/winston/Documents/GitHub/Prime-Calculator/compression/Java/compressor/app/src/main/java/compressor/compressed.txt";
        String decompressOutputName = "/home/winston/Documents/GitHub/Prime-Calculator/compression/Java/compressor/app/src/main/java/compressor/decompressed.txt";

        // Compress File
        System.out.println("\nCompressing file: " + inputFileName);

        compressor.compressFile(inputFileName, outputFileName);

        // Decompress File
        System.out.println("\nDecompressing file: " + outputFileName);

        String inputName = "Test.txt";

        compressor.decompressFile(outputFileName + ".snappy", decompressOutputName);
    }

}

